[package]
name = "clean_ds_store"
version = "0.1.0"
edition = "2021"
authors = ["Your Name"]

[[bin]]
name = "clean-ds-store"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
trash = "5.2"
walkdir = "2.5"
anyhow = "1.0"
colored = "2.1"
